version: "3.7"
services:
  # 服务名称
  rabbitmq:
    # 镜像
    image: rabbitmq:management
    # 端口
    ports:
      - 5672:5672 #集群内部访问的端口
      - 15672:15672 #外部访问的端口
    container_name: rabbitmq
    # 重启策略
    restart: always
    #挂载
    volumes:
      - ./data:/var/lib/rabbitmq
    #环境变量
    environment:
      - RABBITMQ_DEFAULT_VHOST=my_vhost
      - RABBITMQ_DEFAULT_USER=admin #用户名
      - RABBITMQ_DEFAULT_PASS=admin #密码
    # 网络
    #    networks:
    #      - ccloud
    # 主机名
    # hostname: my-rabbit
  # 服务名称
  server:
    image: server:latest
    ports:
      - 12345:12345
    container_name: server
    restart: always


#networks:
#  ccloud:
